version: '3.8'

services:
  # Backend FastAPI service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: qr-generator-backend
    ports:
      - "8000:8000"  # Backend API port
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    volumes:
      - ./backend:/app  # Mount for development (remove in production)
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - qr-network

  # Frontend static file server
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: qr-generator-frontend
    ports:
      - "3000:80"  # Frontend web server port
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - qr-network

  # Nginx reverse proxy (optional, for production)
  nginx:
    image: nginx:alpine
    container_name: qr-generator-proxy
    ports:
      - "80:80"     # Main web port
      - "443:443"   # HTTPS port (configure SSL certificates as needed)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - qr-network

# Network for service communication
networks:
  qr-network:
    driver: bridge

# Volumes for persistent data (if needed)
volumes:
  app-data: